# permissions for end users to edit ixiatgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ixiatg-editor-role
rules:
- apiGroups:
  - network.keysight.com
  resources:
  - ixiatgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.keysight.com
  resources:
  - ixiatgs/status
  verbs:
  - get
