# permissions for end users to view ixiatgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ixiatg-viewer-role
rules:
- apiGroups:
  - network.keysight.com
  resources:
  - ixiatgs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.keysight.com
  resources:
  - ixiatgs/status
  verbs:
  - get
