name: Build

on: [push, pull_request, workflow_dispatch, repository_dispatch]

jobs:
  cicd:
    runs-on: [self-hosted, linux, Ubuntu, x64, docker]
    strategy:
      max-parallel: 1

    steps:

      - name: Give Permission
        run: |
          sudo chown -R $USER:$USER /home/$USER/actions-runner/_work/ixia-c-operator
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Building Artifacts
        run: |
          sudo chmod u+x ./do.sh
          sudo ./do.sh cicd_build

      - name: Running Sanity & Publishing Artifacts
        run: |
          sudo chmod u+x ./do.sh
          sudo ARTIFACTORY_KEY=${{ secrets.ARTIFACTORY_KEY }} ARTIFACTORY_USER=${{ secrets.ARTIFACTORY_USER }} EXPECTED_SANITY_PASS_RATE=${{ secrets.EXPECTED_SANITY_PASS_RATE }} TESTBED=${{ secrets.TESTBED }} TESTBED_PASSWORD=${{ secrets.TESTBED_PASSWORD }} TESTBED_USERNAME=${{ secrets.TESTBED_USERNAME }} ./do.sh cicd_test

      
      - name: Cleaning-Up Testbed
        if: always()
        run: |
          sudo chmod u+x ./do.sh
          sudo TESTBED=${{ secrets.TESTBED }} TESTBED_PASSWORD=${{ secrets.TESTBED_PASSWORD }} TESTBED_USERNAME=${{ secrets.TESTBED_USERNAME }} ./do.sh unlock